### ISSUE TITLE
SMC MH step, resampling and the ESS.

### ISSUE THREAD

**Issue by iamdavecampbell** [mikegros/cnosmc#6]
In cno_smc.R, when the ESS is too small we are doing MH and otherwise resampling at each stage.  
We should be doing MH at every stage and only resample if ESS is too small.

See for example Algorithm 3.1.1 of this paper:  http://www.stats.ox.ac.uk/~doucet/delmoral_doucet_jasra_sequentialmontecarlosamplersJRSSB.pdf

**Comment by mikegros** [comment]
The branch issue6 now reflects this change: resampling if ESS < n_samples/2, always doing MH at each stage. Tested successfully on simple, 3-node graph. Will merge into master after testing confirmed on the larger toy problem.
